Beta test/home -> Dev
WildCodeSchool/2022-03-JS-Toulouse-project-2-happywastes pull request #44
Opened 2022-04-14 15:20 UTC by JoeriKaiser

Désolé Anas, on pensais pas que ça allais te mettre toutes les pulls requests ensemble, on fera composant par composant la prochaine fois.. :(

2022-04-14 15:38 UTC, bastienwcs requested changes

2022-04-14 15:38 UTC, bastienwcs commented on package.json
> +    "react-router-dom": "^6.3.0"
ce fichier ne doit pas être modifié (dans la racine du projet)

2022-04-14 15:38 UTC, bastienwcs commented on package-lock.json
> +      "dependencies": {
ce fichier ne doit pas être modifié (dans la racine du projet)

2022-04-14 15:52 UTC, AnasMama reviewed
Fichier vide à enlever de la PR
![Capture d’écran de 2022-04-14 17-49-56](https://user-images.githubusercontent.com/87085659/163426809-4090a4c2-c018-40f2-b854-f48256900825.png)

2022-04-14 15:58 UTC, AnasMama commented on frontend/src/components/Common/NavBottom/NavBottom.jsx
> -      <div className="NavBottom-Top">
class à mettre en kebab-case

2022-04-15 06:52 UTC, bastienwcs commented
Attention, il ne faut pas faire de commit sur une branche en cours de Pull Request :)
Sinon c'est comme valider le code dans des sables mouvants :rofl:

2022-04-15 06:57 UTC, bastienwcs requested changes

2022-04-15 06:57 UTC, bastienwcs commented on frontend/src/components/Common/NavBottom/NavBottom.css
> +
ligne vide

2022-04-15 06:57 UTC, bastienwcs commented on frontend/src/pages/BigMap.jsx
> +// [43.604652, 1.444209]
ligne à supprimer

2022-04-15 06:57 UTC, bastienwcs commented on frontend/src/pages/Dashboard.jsx
> +// import BackButton from "../components/BackButton/BackButton";
pas de code mort (code commenté) : fichier à supprimer de la PR

2022-04-15 12:43 UTC, JoeriKaiser commented on frontend/src/components/Common/NavBottom/NavBottom.css
> +
C'est reglé

2022-04-15 12:43 UTC, JoeriKaiser commented on frontend/src/pages/Dashboard.jsx
> +// import BackButton from "../components/BackButton/BackButton";
C'est reglé

2022-04-15 12:43 UTC, JoeriKaiser commented on frontend/src/pages/BigMap.jsx
> +// [43.604652, 1.444209]
C'est reglé

2022-04-15 12:44 UTC, JoeriKaiser commented on frontend/src/components/Common/NavBottom/NavBottom.jsx
> -      <div className="NavBottom-Top">
C'est reglé

2022-04-15 12:57 UTC, JoeriKaiser commented on frontend/src/components/Common/NavBottom/NavBottom.css
> +
C'est reglé

2022-04-15 12:57 UTC, JoeriKaiser commented on frontend/src/pages/Dashboard.jsx
> +// import BackButton from "../components/BackButton/BackButton";
C'est reglé

2022-04-15 13:03 UTC, bastienwcs approved these changes
C'est validé :medal_sports:

2022-04-15 13:05 UTC, merged