Installed Framer-Motion. Added global animations to popups, navbar, page transitions and map favourites
WildCodeSchool/2022-03-JS-Toulouse-project-2-happywastes pull request #85
Opened 2022-04-28 08:06 UTC by JoeriKaiser

Run npm install in /frontend to install Framer motion

2022-04-28 10:26 UTC, piment approved these changes

2022-04-28 13:49 UTC, bastienwcs requested changes

2022-04-28 13:49 UTC, bastienwcs commented on frontend/src/pages/Dashboard.jsx
> +            {" "}
Espace inutile à supprimer

2022-04-28 13:49 UTC, bastienwcs commented on frontend/src/pages/Dashboard.jsx
> +              {" "}
espace à supprimer

2022-04-28 13:49 UTC, bastienwcs commented on frontend/src/pages/Dashboard.jsx
> +const variants = {
tu as 4 fois le même objet variant, tu pourrias le mettre dans un fichier js style animation.js et l'importer aux 4 endroits :)

2022-04-29 09:14 UTC, bastienwcs requested changes
Problème de litner suite à la résolution des conflits : 

Error:    3:8   error  'MainMenu' is defined but never used  no-unused-vars
Error:   15:9   error  Delete `··`                           prettier/prettier
Error:   16:11  error  Delete `··`                           prettier/prettier
Error:   17:1   error  Delete `··`                           prettier/prettier
Error:   18:13  error  Delete `··`                           prettier/prettier
Error:   19:1   error  Delete `··`                           prettier/prettier
Error:   20:1   error  Delete `··`                           prettier/prettier
Error:   21:13  error  Delete `··`                           prettier/prettier
Error:   22:11  error  Delete `··`                           prettier/prettier
Error:   23:1   error  Delete `··`                           prettier/prettier
Error:   23:16  error  'MenuList' is not defined             react/jsx-no-undef
Error:   24:13  error  Delete `··`                           prettier/prettier
Error:   25:11  error  Delete `··`                           prettier/prettier
Error:   26:1   error  Delete `··`                           prettier/prettier

2022-04-29 09:21 UTC, bastienwcs commented
récupérer le projet en local (git pull origin labranche)
et faire npm run fix

2022-04-29 09:25 UTC, piment reviewed
Change ' to "

2022-04-29 09:26 UTC, bastienwcs approved these changes

2022-04-29 09:27 UTC, merged