Utils/collect centers
WildCodeSchool/2022-03-JS-Toulouse-project-2-happywastes pull request #93
Opened 2022-05-05 14:43 UTC by piment

2022-05-05 15:01 UTC, Lucas-jimenez-dev approved these changes
ok pour moi

2022-05-05 15:11 UTC, bastienwcs requested changes

2022-05-05 15:11 UTC, bastienwcs commented on frontend/src/services/UserUtils.js
> +        // [this.favourites] = response.data;
à supprimer

2022-05-05 15:11 UTC, bastienwcs commented on frontend/src/services/utils.js
> +// export default { utilFavourites, collectCenters };
à supprimer

2022-05-09 10:19 UTC, bastienwcs approved these changes

2022-05-09 10:19 UTC, bastienwcs commented
BEau boulot :muscle:

2022-05-09 12:18 UTC, merged